name: Build and Publish
run-name: Build and Publish
on: [push]

jobs:
  Build-and-Publish:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🔎 The name of your branch is ${{ gitea.ref }} and your repository is ${{ gitea.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ gitea.repository }} repository has been cloned to the runner."
      -
        # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: https://github.com/docker/setup-qemu-action@v2
      -
        name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2
      # - run: echo "Build finished."
# name: Build and push container
# run-name: Build and push container
# on:
#   push:
#     branches:
#       - 'main'

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3
      # - name: Setup Docker buildx
      #   uses: docker/setup-buildx-action@v2
      # - name: Log into registry
      #   uses: docker/login-action@v2
      #   with:
      #     registry: gitea.loeksangers.nl
      #     username: ${{ gitea.actor }}
      #     password: ${{ secrets.Token }}
      # - name: Build and push Docker image
      #   id: build-and-push
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: .
      #     tags: lsangers/Home:latest